# open ai
Authorization: Bearer "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"

# kintone REST API requests
@domain = nancy-v@kintone.com
@appId = 3
@apiToken = ybpuAL6wTujk1lczjWu8Q1ojLlxQAWMdvet7Sjyi

### GET
GET https://{{domain}}/k/v1.records.json?app={{appId}}
X-Cybozu-API-Token: {{apiToken}}