# open ai
OpenAI-Beta: assistants=v1
Authorization: Bearer "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"

# kintone REST API requests
@domain = nancy-v@kintone.com
@appId = 3
@apiToken = ybpuAL6wTujk1lczjWu8Q1ojLlxQAWMdvet7Sjyi
@recordId = 8

### GET
GET https://{{domain}}/k/v1.record.json?app={{appId}}&id={{recordId}}
X-Cybozu-API-Token: {{apiToken}}